### ISSUE TITLE
 Layer Title and Dot Indicator Not Updating with NiceView Gem

### ISSUE THREAD

**Issue by Notaduck** [M165437/nice-view-gem#1] opened 2024-11-04 21:17 UTC
Hi there! I've been experimenting with the NiceView gem, and it’s working great! However, I’ve noticed that the layer title isn't displayed, and the dot indicators at the bottom don't update when switching layers. Are there any specific configurations or steps I need to follow to get this functionality working?

Here's a link to my ZMK configuration: [zmk-chocofi-config](https://github.com/Notaduck/zmk-chocofi-config).

Thank you for your help!

**Comment by M165437** [comment] 2024-11-10 18:57
Hey! Do layer title and profile indicator work with the default nice!view shield?

```
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_custom 
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_custom
```

**Comment by Notaduck** [comment] 2024-11-14 21:19
I just tried with the `nice_view` shield and that works flawless. Btw, the dots do change when I switch BT profiles.

it is just the layers which doesn't change on the nice!view.

**Comment by rael-dev** [comment] 2024-12-11 20:02
Hello, I am having the same issue with the layer name and dots not updating properly.  Using `nice_view_custom` failed my keymap build when I tried that. Any ideas for how to get the layer aspect working? Ideally, I would love to be able to remove the WPM widget and move the layer name up to take its place. Is that possible through configuration?

**Comment by kirsi** [comment] 2024-12-18 07:08
Hey, i love this widget and it's working on my wireless Lily58. But as the others are already mentioned, the Layer display is not showing any name and the dots are "frozen". Any chance you can update this? My [config](https://github.com/kirsi/lily58-config)

**Comment by rael-dev** [comment] 2024-12-22 01:16
I believe I found the answer to the problem. Well at least half of it (only the layer text). I forked the repo because I wanted to fix the issues and get rid of the WPM widget, and I found out that the issue is with each of our keymaps. The `layer.c` file is looking for the layer's label property to determine the text that shows up. It is supposed to default to using the text "Layer x" but that check looks to see if the label is `NULL` so I think this doesn't work because the property might default to an empty string. I took a look at @Notaduck's, @kirsi's, and my own to compare them to @M165437's and noticed that for each of our layers we do not include a label property. (Interestingly the message `'label' is marked as deprecated in 'properties:'` will show in the West build when using these)

So based on the corne keymap you linked, you would change each of your layers from something like:
```
base_layer { 
      bindings = <...>;
};
```
    
To this:

```
base_layer { 
      label = "base"; // they get forced to uppercase
      bindings = <...>;
};
```
    
This worked for me for updating the text but I am still working on understanding why we don't get the layer boxes to update properly. It may be related to something in our config .conf files but I haven't pinpointed it.

Another interesting thing I ran into was my keyboard freezing/crashing whenever I used the label "Navigation" (10 characters) for one of my layers. I think this ended up causing an overflow with the `strcpy` in `layer.c` whenever I would try to switch over to that layer. The issue went away when I switched the label to "NAV". The longest label I have successfully used is 7 characters.

**Comment by rael-dev** [comment] 2024-12-22 02:54
I dug a little more and found the issue with the "frozen" dots.

In the `profile.c` file it is using the wrong member of the `status_state` struct to calculate the offset used to draw the active profile:

```
static void draw_active_profile(lv_obj_t *canvas, const struct status_state *state) {
    lv_draw_rect_dsc_t rect_white_dsc;
    init_rect_dsc(&rect_white_dsc, LVGL_FOREGROUND);

    int offset = state->active_profile_index * 7;

    lv_canvas_draw_rect(canvas, 18 + offset, 129 + BUFFER_OFFSET_BOTTOM, 3, 3, &rect_white_dsc);
}
```

I changed my offset calculation to be `int offset = state->layer_index * 7;` and the correct offset is calculated and my dots are not frozen. Perhaps there was some confusion when writing this function because in the `screen.c` file the `set_layer_status()` function updates the state like this `widget->state.layer_index = state.index;` and the member `active_profile_index` is actually never used.

**Comment by M165437** [comment] 2024-12-23 12:45
That's awesome, thank you for your efforts! I'm on a longer vacation and didn't bring my split keyboard, so I can't test it and debug myself. Would you be willing to open a PR in the mean time? I'd check and merge it when I'm back.

**Comment by rael-dev** [comment] 2024-12-23 19:57
No problem, I am actually now on a vacation for the holidays as well (and didn't bring my keyboard either lol), but before I took off I did make that change and observed it working properly on my corne. I created the PR so that you can check that out whenever you get a chance!

**Comment by M165437** [comment] 2024-12-26 05:32
Oh wait, I think there is a confusion. The dot is indicating the active profile, not the active layer. The keyboard can be connected to several machines at the same time. You can switch between using the keyboard with your laptop and your desktop pc. So "active_profile_index" is actually correct. I think you were expecting the dots to change together with the layer name.

**Comment by rael-dev** [comment] 2024-12-26 13:57
Oh! That makes total sense then, I was definitely confused about that one. In that case then the only fix needed was the inclusion of the `label` for each keymap layer. Thanks!

**Closed** 2024-12-26 14:31 UTC
